from enum import Enum, unique


@unique
class ItemSpell(Enum):

    BLINDNESS = "blindness"
    CALL_LIGHTNING = "call lightning"
    CALM = "calm"
    CAUSE_SERIOUS = "cause serious"
    CHARM_PERSON = "charm person"
    CLONE = "clone"
    CONTROL_WEATHER = "control weather"
    CREATE_WATER = "create water"
    CURE_BLIND = "cure blind"
    CURE_CRITIC = "cure critic"
    CURE_LIGHT = "cure light"
    CURE_SERIOUS = "cure serious"
    CURSE = "curse"
    DETECT_INVISIBILITY = "detect invisibility"
    EARTHQUAKE = "earthquake"
    ENCHANT_WEAPON = "enchant weapon"
    ENERGY_DRAIN = "energy drain"
    FIREBALL = "fireball"
    FIREBLAST = "fireblast"
    FLY = "fly"
    HARM = "harm"
    HEAL = "heal"
    ICE_STORM = "ice storm"
    IDENTIFY = "identify"
    INVISIBLE = "invisible"
    LIGHTNING_BOLT = "lightning bolt"
    MAGIC_MISSILE = "magic missile"
    PETRIFICATION = "petrification"
    POISON = "poison"
    PROTECTION_FROM_EVIL = "protection from evil"
    PROTECTION_FROM_GOOD = "protection from good"
    REJUVENTATE = "rejuvenate"
    REMOVE_POISON = "remove poison"
    SANCTUARY = "sanctuary"
    SENSE_LIFE = "sense life"
    SLEEP = "sleep"
    STRENGTH = "strength"
    TELEPORT = "teleport"
    WATERWALK = "waterwalk"
    WORD_OF_RECALL = "word of recall"
